//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeyadMaged_DesktopAssesment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int userid { get; set; }
        public string usUsername { get; set; }
        public string usPassword { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Phonenumber { get; set; }
        public string City { get; set; }
    }
}
